### ISSUE TITLE
Java deploy docs incorrect for Spring Boot?

### ISSUE THREAD

**Issue by tedyoung** [railwayapp/docs#102]
I (successfully!) deployed a Spring Boot-based project and I did not need the "copy dependencies" plugin, nor a `Procfile`. I only needed to add a `system.properties` to have it use Java 17.

I'm not sure if the plugin or procfile is needed for other frameworks, but might be worth calling out Spring Boot separately due to its popularity.

**Comment by ndneighbor** [comment]
This is good feedback- I personally think we are a little light when it comes to Java documentation and will keep this in mind when we do the revamp happening soon.

With Railway, we want there to be as little config as possible so if it works out of the box that's great- but wanna expose the magic that's happening under the hood.

**Comment by tedyoung** [comment]
Let me know if you need feedback on updates to Java-related docs.

**Comment by brody192** [comment]
We have new language and framework guides now, one of the new additions being spring boot -

https://docs.railway.com/guides/spring-boot
