### ISSUE TITLE
deploy/builds lang specific links are broken when following in app doc links

### ISSUE THREAD

**Issue by philkuz** [railwayapp/docs#117]
Was trying to learn more about golang build, but  the docs don't work for any of the languages, instead the page is 404-ing.

Offending page https://docs.railway.app//deploy/builds I got there by clicking this docs link: 
![image](https://user-images.githubusercontent.com/5456019/161389746-55c808ec-d478-4190-9fd7-1b538ab7cf59.png)

![image](https://user-images.githubusercontent.com/5456019/161389682-cb104f0f-4a59-491a-a016-24b9b6e116db.png)
Link for `go`:https://docs.railway.app//deploy/go
But I get redirected to https://docs.railway.app/go

I think something is wrong with the double forward slash // that I got from the link. Also is weird that docs don't accept that url route either.

**Comment by half0wl** [comment]
This should be fixed. We've removed those sections entirely and link out to https://nixpacks.com/docs instead.
