### ISSUE TITLE
Default Python Version?

### ISSUE THREAD

**Issue by invictus2010** [railwayapp/docs#136]
Hi there! I'm a bit of a newbie so I didn't want to open up a PR without asking the question.

The [Python docs for Railway](https://docs.railway.app/deploy/python) state, "The default Python version is 3.6." When I run `railway up`. I see the following: "Using the buildpack default: 3.10.5." Should I open a PR to update the Railway docs, or is this buildpack default different than what the Railway docs are discussing? 

<img width="927" alt="Screen Shot 2022-07-05 at 6 19 15 PM" src="https://user-images.githubusercontent.com/17661001/177426810-2aafddc7-1135-4dcd-8a6e-942a014ba5f2.png">

**Comment by half0wl** [comment]
You're correct, it uses the default version in Heroku's buildpack.

FYI, this was removed from the Railway docs altogether (for the same reasons you opened this issue, it's confusing!), so I'm closing this out.
