### ISSUE TITLE
Possible clarification needed when deploying local changes.

### ISSUE THREAD

**Issue by stormwild** [railwayapp/docs#178]
Currently the Getting Started doc states:

> Once you are done, save the file. In the next step, we will show you how easy it is to deploy your changes.

It seems to imply that this would deploy any uncommitted and un-pushed local changes. We may want to include the clarification of needing to commit and push local changes.

> Once you are done, save the file, commit and push to your repo. In the next step, we will show you how easy it is to deploy your changes.

It seems `railway up` only deploys the latest commit of the main branch. Not uncommitted changed files on our local directory.

PR for review: https://github.com/railwayapp/docs/pull/179

**Comment by shardayyyy** [comment]
It looks like committing only applies to linked GitHub repos. If you are using the railway cli, it seems "railway up" should be sufficient enough to push any new changes before they are committed.
