### ISSUE TITLE
Nixpacks option can't be selected once Docerfile is detected in repo

### ISSUE THREAD

**Issue by Krajmark** [railwayapp/docs#206]
Hi, so I have a Dockerfile in my repo but I dont want to use it as the template for building the deployment image, however the select buildtool option disappears as soon as the Dockerfile is detected in the repo. I also dont want to have to rename the Dockerfile so it doesn't get detected by default. Is there any way to re-enable Nixpacks for instance in this case.
![image](https://user-images.githubusercontent.com/99593444/219871319-96bb54a9-f88a-49d5-9898-3971db56e57f.png)

**Comment by ItsGoldeneyes** [comment]
If you need help, please join the Discord server. This is not an issue with the docs.

If a dockerfile named dockerfile is found in the root directory it will always be used. To get around this, rename the dockerfile. Railway does not detect renamed dockerfiles

**Comment by Krajmark** [comment]
Ok, thanks I just hoped there is an other way
