### ISSUE TITLE
Legal page not opening when account is banned

### ISSUE THREAD

**Issue by Anuragd275** [railwayapp/docs#207]
This is what I see when I try to login
# End of the Line 
You've been flagged for violations concerning the Railway [ToS](https://railway.app/legal). The reason specified is "not mentioning my reason here :)"

If you believe this is in error; please reach out to us via [email](https://docs.google.com/forms/d/e/1FAIpQLSd8AGaX_7fMgjhCwIFjmRn101BZ8dOa6w44qUL2RT3JOrUzag/viewform?usp=sf_link) and we'll get you sorted!

This process is automated, new, and in constant evolution. Apologies for any inconvenience.

## When I click on ToS the url on the searchbar changes but nothing happens.

I am facing this on the main page and there is no repo for the main page so I opened this issue here. (Sorry for this)

**Comment by dw-liedji** [comment]
hello! Please, how did you solve this issue? I have the same problem and don't have multiple accounts. This problem has shut down all my applications are not working. It is a very bad experience for me.

**Comment by Anuragd275** [comment]
> hello! Please, how did you solve this issue? I have the same problem and don't have multiple accounts. This problem has shut down all my applications are not working. It is a very bad experience for me.

Hi, this issue is not resolved, I tried to contact Railway support through mail and their Discord server but I received **no response** from Railway.

When I asked about it on their Discord server, I was muted for 1 hour. Because of this I had to shift on the Render.

**Comment by dw-liedji** [comment]
Thank you for your response @Anuragd275, I am not able to even open my existing Heroku applications that use Railway to store the Postgres SQL database.  I am worried about all my data stored on their servers. I cannot just switch to another provider because I used to like the service they provide and also all my data are in their database. Please, what can I do about this issue? It is blocking all our applications using Railway for database storage.

**Comment by Anuragd275** [comment]
> Thank you for your response @Anuragd275, I am not able to even open my existing Heroku applications that use Railway to store the Postgres SQL database.  I am worried about all my data stored on their servers. I cannot just switch to another provider because I used to like the service they provide and also all my data are in their database. Please, what can I do about this issue? It is blocking all our applications using Railway for database storage.

Hey @dw-liedji, Sorry to hear this but I didn't store any important information on Railway's Platform, So I can't help you here however you can try to contact Railway and if you're lucky they might respond in a few days.

Mail : contact@railway.app 

Try to ask about it on their Discord server. (Use incognito mode or other browser to open railway.app and find their Discord server Invite link)

I hope this helps.

**Comment by dw-liedji** [comment]
Thank @Anuragd275 for your support. I have sent an email to [contact@railway.app](mailto:contact@railway.app). Hoping they will respond.
