### ISSUE TITLE
Add anchor tags to section headers

### ISSUE THREAD

**Issue by half0wl** [railwayapp/docs#246]
https://cdn.discordapp.com/attachments/1100364112862646332/1100364494372352080/CleanShot_2023-04-25_at_03.15.192x.png

This allows us to link out to any section without scrolling up to the ToC sidebar on the right.

**Comment by samridht23** [comment]
[railwayfix.webm](https://user-images.githubusercontent.com/75132459/235430045-77a62440-7a09-41d4-9dcf-9737982df4e8.webm)

i made a pr that will add the (#) fragment-identifier to the titles but i was not able to overwrite the span that which was already present there.
 
![railwayfix](https://user-images.githubusercontent.com/75132459/235430838-4cfb6eff-6a96-4b49-8061-9550840d0140.png)

**Comment by half0wl** [comment]
Closed in #261
