### ISSUE TITLE
Anchor links sometime do not take you directly to the section it belongs to

### ISSUE THREAD

**Issue by half0wl** [railwayapp/docs#250]
I can't reproduce this reliably, but go to https://docs.railway.app/reference/cli-api and click around anchor links and you'll land on a different section than intended after a few clicks.

This seems related to https://github.com/vercel/next.js/issues/44295

**Comment by artimath** [comment]
@half0wl this is likely unrelated to this specific issue, and the marketing site is likely a different repo... 

but worth noting here that the "main career page" links in job pages link to the same job page. reported with screen record in [discord](https://discord.com/channels/713503345364697088/872280333167517736/1157420137377452084). happens on both safari ios and chrome mac for me.

<img width="1728" alt="2023-09-29_11-39-53" src="https://github.com/railwayapp/docs/assets/19831746/d6bc9346-9c49-42d7-9680-2df861c35340">

**Comment by artimath** [comment]
Also, can confirm that the original issue here happens still on my machine. I might take a look and report back.

**Comment by Teejay128** [comment]
Hello all, I think this issue has been resolved, or at least I haven't been able to reproduce the issue described above by clicking on the links highlighted in the image below.
![image](https://github.com/user-attachments/assets/83633c75-c3ee-4671-bdf1-94d111087456)

**Comment by brody192** [comment]
This was fixed in #558
