### ISSUE TITLE
need to run `yarn add npm-run-all --dev`

### ISSUE THREAD

**Issue by aaronhmiller** [railwayapp/docs#265]
following the install and getting started guide, before running `railway run yarn dev`, I had to do the `yarn add npm-run-all dev` step. Otherwise, I kept getting lots of `command not found` errors. Might be worth adding to the doc if you expect folks who are newbs like me to all this.

**Comment by half0wl** [comment]
> following the install and getting started guide, before running `railway run yarn dev`, I had to do the `yarn add npm-run-all dev` step. Otherwise, I kept getting lots of `command not found` errors. Might be worth adding to the doc if you expect folks who are newbs like me to all this.

Hey, can you link the page this is on?

**Comment by aaronhmiller** [comment]
Thanks @half0wl didn't see your comment until just now. 😅 

It's on this page: https://docs.railway.app/getting-started
about ⅔ of the way down...search for `railway run yarn dev` and you'll be in the spot I'm referring to.
