### ISSUE TITLE
Clear search results when query input is empty

### ISSUE THREAD

**Issue by half0wl** [railwayapp/docs#266]
1. Enter some text
2. Delete it
3. Query results are still present, it should not be

Suggested by @brody192

**Comment by jobayer12** [comment]
@half0wl 
Can anyone give some instructions on how to setting up meilisearch? Basically, I'm new here. I can't set up this project properly in the local environment. It would be helpful if anyone gives some instructions for setting up this project in the local environment.

**Comment by tarunsamanta2k20** [comment]
@half0wl Unhandled Runtime Error
MeiliSearchError: The provided host is not valid.

**Comment by TruePadawan** [comment]
I've addressed this in this [pull request](https://github.com/railwayapp/docs/pull/277)

**Comment by half0wl** [comment]
Fixed in #277 by @TruePadawan
