### ISSUE TITLE
End of The Line error when login to my account

### ISSUE THREAD

**Issue by dw-liedji** [railwayapp/docs#289]
Hello, my friends at Railway, 

I have tried to login into my railway account today but I have the following blocking error popping up:

"You've been flagged for violations concerning the Railway [ToS](https://railway.app/legal). The reason specified is "Multiple accounts".
If you believe this is in error; please reach out to us via [email](https://docs.google.com/forms/d/e/1FAIpQLSd8AGaX_7fMgjhCwIFjmRn101BZ8dOa6w44qUL2RT3JOrUzag/viewform?usp=sf_link) and we'll get you sorted!

This process is automated, new, and in constant evolution. Apologies for any inconvenience."

**I only have one account please resolve this issue. All my Postgres applications have stopped working. Please resolve it.**

**Comment by dw-liedji** [comment]
Dear Railway Support Team,

I hope this message finds you well. I am writing to bring your attention to a critical issue that is preventing me from logging into my Railway account and causing disruptions to all my applications. The issue is titled "End of the Line."

Upon attempting to log in, I am encountering a blocking message that states:

"You've been flagged for violations concerning the Railway Terms of Service. The reason specified is 'Multiple accounts'."

I would like to clarify that I do not have multiple accounts, and this misunderstanding is now affecting all my applications hosted on your servers. The situation is becoming increasingly problematic for me, and I urgently seek your assistance in resolving this matter.

I kindly request your immediate attention to my account in order to rectify this issue. It is imperative that I regain access to my account and restore the functionality of my applications as soon as possible. The disruption caused by this blocking message is significantly impacting my work and causing immense inconvenience.

I understand that your processes are automated and constantly evolving. However, I kindly ask for your understanding and prompt resolution of this situation. If further information or clarification is required, please do not hesitate to reach out to me via email at [liedjiwenkack@gmail.com](mailto:liedjiwenkack@gmail.com)

I sincerely appreciate your attention to this matter and your swift action in resolving the blocking issue. Your prompt response and assistance will be of great help in alleviating the problems I am currently facing.

Thank you for your understanding and cooperation.

Yours sincerely,
Liedji

**Comment by half0wl** [comment]
@dw-liedji:

Our open source repositories are NOT a support channel.

I've unblocked your account as I believe this to be a genuine mistake on our part (sorry!), but I want to re-iterate that this is unacceptable conduct moving forward. If you need help, please out to us via the appropriate channels (https://docs.railway.app/reference/support).

> It is imperative that I regain access to my account and restore the functionality of my applications as soon as possible.

Check out https://docs.railway.app/reference/support#business-class if you're supporting critical production workloads.
