### ISSUE TITLE
Feedback UI 

### ISSUE THREAD

**Issue by kerolloz** [railwayapp/docs#290]
Clicking yes on did you find this post helpful shows the following: 

<img width="798" alt="Screenshot 2023-06-26 at 2 36 17 PM" src="https://github.com/railwayapp/docs/assets/36763164/a3d75203-544a-418d-99bf-ef0f06ededad">

**Comment by kerolloz** [comment]
https://github.com/railwayapp/docs/assets/36763164/c9dc1e35-28e5-44a9-bd1b-5f97f68627b9


https://github.com/railwayapp/docs/assets/36763164/71632b73-7f2d-459c-9c52-23db47aabd0f

**Comment by half0wl** [comment]
Fixed in #293

**Comment by kerolloz** [comment]
@half0wl Great.
Good job @samridht23!
