### ISSUE TITLE
Is postgres still version 13?

### ISSUE THREAD

**Issue by cktang88** [railwayapp/docs#320]
It links to https://hub.docker.com/r/timescale/timescaledb which has v15 so just wondering

**Comment by half0wl** [comment]
It's v13 as specified in the text:
![ss 2023-08-14 at 9 55 40 PM](https://github.com/railwayapp/docs/assets/24421625/e55e0454-e668-4f68-bae9-bb3153784e78)

I don't think we can link out to a specific image tag, but it'd be nice to link directly to the image SHA we're using. Nice catch!

**Comment by cktang88** [comment]
Ah ok, is there a plan to move to v14/15 anytime?

**Comment by junepark202012** [comment]
I'm also curious

**Comment by half0wl** [comment]
Yep! We're moving to a model where users can use any version they want, while Railway maintains some versions officially. This goes for all databases (not just Postgres). Work is currently underway to power all of this (priv networking, volumes, better template creation/maintainence flows, etc.) and we'll share more (+migration guides) soon!

I'm locking this as it's irrelevant to docs, please submit any further questions to https://discord.gg/railway. Thanks 🙏🏻
