### ISSUE TITLE
Documentation on Scaling

### ISSUE THREAD

**Issue by bishwenduk029** [railwayapp/docs#33]
HIi,

I love this deployment ideology having your production mirrored into your local to the bone can really help anyone take off very fast. Just one small request if you could also provide some information on how scale post deployment that could be also very helpful.

**Comment by rpxs** [comment]
Define scaling I guess? Do you want to know how the usage base pricing works as your app scales, or just best practices for scaling an app?

**Comment by bishwenduk029** [comment]
Sorry for late response. I did not find any configurations on how scale my deployment on Railways. Like which regions I can deploy to and how Railways handle autoscaling and its relation to pricing.

**Comment by rpxs** [comment]
Railway currently only supports the US as a region. There are going to be servers in Europe soon, but there are a couple internal legal things that need to be resolved before that happens. 

As of autoscaling, if your app is exceeding provided limits and you haven't linked a payment method, Railway will limit your resources and send you an email to notify you that you've hit the limits. If you **have** linked a payment method, Railway will automatically provision the needed resources, and you will then adhere to the usage based pricing model if I remember correctly.

**Comment by bishwenduk029** [comment]
Thank you so much for your response it makes sense.

**Comment by cnicodeme** [comment]
Hi,
I'm updating this because I have further questions.

@rpxs you mention that you will soon support the Europe region. Is it good now? I'm testing Railway and like it so far, but needs my servers to be located in Europe (or GDPR issues).

As for auto-scaling, can you confirm that if we have a peak of usage, I don't have to worry about anything, and Railway will take care of scaling up and down?

Thanks for these clarifications.

**Comment by nonlinearcom** [comment]
Same question here, is there any update ETA for EU servers? 

Thanks!

**Comment by joaorr3** [comment]
Hey @rpxs, do you have any updates for the EU region? 
Thank you

**Comment by joaorr3** [comment]
> Same question here, is there any update / ETA for EU servers?
> 
> Thanks!

@nonlinearcom 
https://feedback.railway.app/feature-requests/p/configurable-deployment-region
