### ISSUE TITLE
Compare to heroku page not found

### ISSUE THREAD

**Issue by finnala** [railwayapp/docs#408]
Hi, if you navigate to the "compare to Heroku" page on the docs, you get a page not found:

<img width="1920" alt="image" src="https://github.com/railwayapp/docs/assets/122728490/ad32bb6d-3492-4e81-a3f9-cc205d104d71">

Which is on route https://docs.railway.app/maturity/compare-to-heroku.

If you go from click the "continue reading" button under "what we offer over heroku" on the main heroku page (https://railway.app/heroku), it takes you to it.
<img width="1920" alt="image" src="https://github.com/railwayapp/docs/assets/122728490/b91fdb99-010d-4889-88c4-646ebad6d20e">
<img width="1920" alt="image" src="https://github.com/railwayapp/docs/assets/122728490/e15d6ef7-eb36-4fa6-803e-0e0de3d21392">

Looks like the `href` on the continue reading button takes you to https://docs.railway.app/reference/compare-to-heroku. 

But, you can't find this tab under "Reference" on docs, and it's instead under the "Maturity" tab which leads to a 404.

I think the ideal fix IMO is to fix the main docs link (put the compare to heroku docs under migrate), and then adjust the link on the https://railway.app/heroku page.

**Comment by melissa-hale** [comment]
Hi @finnala, thank you for raising!  I have corrected this via a redirect.
