### ISSUE TITLE
Light theme for Pricing page

### ISSUE THREAD

**Issue by rafrafek** [railwayapp/docs#463]
Hello,

Please consider adding a light themed version of the pricing page https://railway.app/pricing

I can't read it currently, it's too dark.

**Comment by brody192** [comment]
This github repository does not contain any pages for the link you have provided, instead, please share this feedback [here](https://help.railway.app/feedback)

**Comment by rafrafek** [comment]
Your link requires me to log in.

But I can't log in, because I have to accept the ToS.

I can't accept the ToS, because I can't read it, because it is blocked by the ToS pop-up on the right, which requires me to accept the ToS before reading it.

And everything is dark there, I can barely see anything.

Can you report all of those for me to the appropriate team?

<img width="1840" alt="image" src="https://github.com/railwayapp/docs/assets/23004737/867d9178-a1fd-4bea-ac47-9ffed48b4ca8">

**Comment by rafrafek** [comment]
> how the page is too dark from your point of view, because I'm not quite understanding how that page is too dark.

Please compare your pricing:

<img width="1840" alt="image" src="https://github.com/railwayapp/docs/assets/23004737/db72ac8c-c3db-494c-a565-c18793acb6c4">


With a light themed pricing on some other website:

<img width="1840" alt="image" src="https://github.com/railwayapp/docs/assets/23004737/1ec0caed-8a22-4591-b7cc-3f04270f81f9">


If you want to know what I see, take your laptop outside in a sunny day and compare the two pictures above, which one is more readable. The pricing page should have both light and dark themes and preferably auto theme switch - sync with OS theme option.

**Comment by rafrafek** [comment]
https://en.wikipedia.org/wiki/Accessibility

**Comment by rafrafek** [comment]
> I can't accept the ToS, because I can't read it, because it is blocked by the ToS pop-up on the right, which requires me to accept the ToS before reading it.

By the way, it's not legal here in Europe.

**Comment by brody192** [comment]
Thank you for sharing your point of view on this, I can understand how that is extremely frustrating for you, I will be sure to bring this valuable feedback to the applicable person asap!

Again, sorry that you've had such a poor experience with the site's accessibility!

**Comment by rafrafek** [comment]
Thank you for your support!

Feel free to close the issue here if it's being tracked elsewhere.

**Comment by brody192** [comment]
I was told that this issue was brought up in their Monday sync, so this has not gone unheard!
