### ISSUE TITLE
Upgrade Node.js (v16 reached end of life) Version and Next.js for Safety & to Leverage Modern Features

### ISSUE THREAD

**Issue by ve-varun-sharma** [railwayapp/docs#537]
# Description
The current documentation for the open-sourced Next.js app for Railway.app is using Node.js version 16.0.0 Node.js version 16 reached its [End-of-Life (EOL) on September 2023](https://nodejs.org/en/blog/announcements/nodejs16-eol), leaving the project vulnerable to security risks and missing out on performance improvements in newer versions.

This issue highlights the need to upgrade the following aspects of the project:

- Node.js: Update to a Long-Term Support (LTS) version like Node.js 18.x or the latest LTS version available at the time of upgrade.
- Next.js: Due to the Node.js version bump, it would be possible to upgrade Next.js to version 14 or the latest stable version, allowing the project to benefit from performance enhancements and new features.

# Benefits of Upgrading:

- Improved Security: Utilizing a supported Node.js version ensures access to security patches and reduces the risk of vulnerabilities.
- Enhanced Performance: Upgrading Next.js can offer improved performance and access to new features in the latest version.
- Modern Development: Maintaining compatibility with current Node.js and Next.js versions allows for safer and more reliable dependency upgrades.

# Proposed Solution:

- Update package.json to specify the latest compatible LTS version of Node.js and the desired Next.js version. This also ensures the app deployed on railway infrastructure use the right node version
- Update any other dependencies in the project that require Node.js version 18 or higher as needed.
- Test the application thoroughly after the upgrade to ensure everything functions as intended.

## Additional Considerations:

- This issue focuses on upgrading Node.js and Next.js versions. It's recommended to review the compatibility of all core project dependencies after the Node.js upgrade.
- We can consider creating a separate pull request for each upgrading the node version and then the next version separately.

## Meme
![image](https://github.com/user-attachments/assets/c33e0608-fb26-46c1-bf24-d71e23c8761a)

**Comment by ndneighbor** [comment]
Closing as both PRs have been merged. Cheers!

**Comment by ve-varun-sharma** [comment]
> Closing as both PRs have been merged. Cheers!

Amazing!!! 🍻  :) Thanks for the speedy resolution on this! 😲  ❤️
